### ISSUE TITLE
Missing file: all_loci_score_matrix.txt

### ISSUE THREAD

**Issue by rio26** [dimiboeckaerts/PhageHostLearn#2]
Hi, I've been working through the training notebook and encountered an issue during the training section 4.2. It seems that the "all_loci_score_matrix.txt" file is not available in either the provided folder or on the Zenodo page (https://zenodo.org/records/8095914). Could you please share this text file? Your assistance would be greatly appreciated.
Thank you!

**Comment by dimiboeckaerts** [comment]
Hi, thanks for your interest in running our code and analyses! You're right, I hadn't uploaded that file yet to Zenodo. I now provided an updated version of the record with the *all_loci_score_matrix.txt* included! Here it is: https://zenodo.org/records/11061100. Just an FYI: you only need this file when you want to recreate our exact evaluation on our exact datasets. If you just care about inference or training a model on your own data, this file is not of use :).

If you have any more questions, feel free to ask.

**Dimi**

**Comment by rio26** [comment]
Many thanks, problem solved!
